import { v4 as uuidv4 } from 'uuid';
import type { KRA } from './types';

export const mockKras: KRA[] = [
  {
    id: 'KRA-001',
    taskDescription: 'Develop and launch the new customer portal by Q3 end.',
    employee: {
      id: 'EMP-001',
      name: 'Alice Johnson',
      avatarUrl: 'https://placehold.co/32x32.png',
      branch: 'Engineering',
    },
    progress: 67,
    status: 'On Track',
    weightage: 15,
    marksAchieved: 10,
    bonus: 0,
    penalty: 0,
    startDate: new Date('2024-07-01'),
    endDate: new Date('2024-09-30'),
    actions: [
      { id: uuidv4(), description: 'Finalize UI mockups', dueDate: new Date('2024-07-15'), isCompleted: true },
      { id: uuidv4(), description: 'Develop backend APIs', dueDate: new Date('2024-08-10'), isCompleted: true },
      { id: uuidv4(), description: 'Frontend implementation', dueDate: new Date('2024-09-01'), isCompleted: false },
    ]
  },
  {
    id: 'KRA-002',
    taskDescription: 'Increase organic search traffic by 20% over the next quarter.',
    employee: {
      id: 'EMP-002',
      name: 'Bob Williams',
      avatarUrl: 'https://placehold.co/32x32.png',
      branch: 'Marketing',
    },
    progress: 25,
    status: 'At Risk',
    weightage: 20,
    marksAchieved: 5,
    bonus: 0,
    penalty: 2,
    startDate: new Date('2024-08-15'),
    endDate: new Date('2024-11-15'),
     actions: [
      { id: uuidv4(), description: 'Keyword research', dueDate: new Date('2024-08-25'), isCompleted: true },
      { id: uuidv4(), description: 'Create 10 blog posts', dueDate: new Date('2024-09-25'), isCompleted: false },
      { id: uuidv4(), description: 'Build 20 backlinks', dueDate: new Date('2024-10-25'), isCompleted: false },
      { id: uuidv4(), description: 'Optimize on-page SEO', dueDate: new Date('2024-11-05'), isCompleted: false },
    ]
  },
  {
    id: 'KRA-003',
    taskDescription: 'Reduce customer support ticket resolution time by 15%.',
    employee: {
      id: 'EMP-003',
      name: 'Charlie Brown',
      avatarUrl: 'https://placehold.co/32x32.png',
      branch: 'Support',
    },
    progress: 90,
    status: 'On Track',
    weightage: 10,
    marksAchieved: 9,
    bonus: 0,
    penalty: 0,
    startDate: new Date('2024-07-10'),
    endDate: new Date('2024-10-10'),
    actions: []
  },
  {
    id: 'KRA-004',
    taskDescription: 'Achieve a 95% customer satisfaction score for Q3.',
    employee: {
      id: 'EMP-004',
      name: 'Diana Prince',
      avatarUrl: 'https://placehold.co/32x32.png',
      branch: 'Support',
    },
    progress: 100,
    status: 'Completed',
    weightage: 15,
    marksAchieved: 15,
    bonus: 2,
    penalty: 0,
    startDate: new Date('2024-07-01'),
    endDate: new Date('2024-09-30'),
    actions: []
  },
  {
    id: 'KRA-005',
    taskDescription: 'Onboard 5 new enterprise clients in the next six months.',
    employee: {
      id: 'EMP-005',
      name: 'Ethan Hunt',
      avatarUrl: 'https://placehold.co/32x32.png',
      branch: 'Sales',
    },
    progress: 20,
    status: 'On Track',
    weightage: 25,
    marksAchieved: 5,
    bonus: 0,
    penalty: 0,
    startDate: new Date('2024-09-01'),
    endDate: new Date('2025-03-01'),
    actions: [
        { id: uuidv4(), description: 'Identify 50 potential leads', dueDate: new Date('2024-09-30'), isCompleted: true },
        { id: uuidv4(), description: 'Conduct 20 product demos', dueDate: new Date('2024-11-30'), isCompleted: false },
    ]
  },
  {
    id: 'KRA-006',
    taskDescription: 'Finalize the 2025 product roadmap.',
    employee: {
      id: 'EMP-006',
      name: 'Fiona Glenanne',
      avatarUrl: 'https://placehold.co/32x32.png',
      branch: 'Engineering',
    },
    progress: 0,
    status: 'Pending',
    weightage: 5,
    marksAchieved: 0,
    bonus: 0,
    penalty: 0,
    startDate: new Date('2024-10-01'),
    endDate: new Date('2024-10-31'),
    actions: []
  },
  {
    id: 'KRA-007',
    taskDescription: 'Sell 1500 units of Product X.',
    employee: {
      id: 'EMP-007',
      name: 'Amara Ray',
      avatarUrl: 'https://placehold.co/32x32.png',
      branch: 'Sales',
    },
    progress: 93,
    status: 'On Track',
    weightage: 15,
    marksAchieved: 14,
    bonus: 0,
    penalty: 0,
    startDate: new Date('2024-09-01'),
    endDate: new Date('2024-12-31'),
    actions: []
  },
   {
    id: 'KRA-008',
    taskDescription: 'Increase customer retention by 5%.',
    employee: {
      id: 'EMP-001',
      name: 'Alice Johnson',
      avatarUrl: 'https://placehold.co/32x32.png',
      branch: 'Engineering',
    },
    progress: 50,
    status: 'On Track',
    weightage: 10,
    marksAchieved: 5,
    bonus: 0,
    penalty: 0,
    startDate: new Date('2024-10-01'),
    endDate: new Date('2024-12-31'),
    actions: []
  },
];
