// This file is automatically generated by Firebase Studio.
// Do not edit this file manually.

'use client';
import { useState, useEffect, useMemo } from 'react';
import {
  onSnapshot,
  query,
  where,
  collection,
  orderBy,
  limit,
  startAt,
  startAfter,
  endAt,
  endBefore,
  doc,
  getDoc,
  Timestamp,
  type DocumentData,
  type CollectionReference,
  type Query,
} from 'firebase/firestore';

interface UseCollectionOptions {
  where?: [string, any, any][];
  orderBy?: [string, 'asc' | 'desc'];
  limit?: number;
  startAt?: any[];
  startAfter?: any[];
  endAt?: any[];
  endBefore?: any[];
}

function processDocValue(value: any): any {
  if (value instanceof Timestamp) {
    return value.toDate();
  }
  if (Array.isArray(value)) {
    return value.map(processDocValue);
  }
  if (value && typeof value === 'object') {
    return Object.keys(value).reduce((acc, key) => {
      acc[key] = processDocValue(value[key]);
      return acc;
    }, {} as { [key: string]: any });
  }
  return value;
}

async function resolveReferences(data: DocumentData, firestore: any): Promise<DocumentData> {
  const resolvedData = { ...data };
  for (const key in resolvedData) {
    const value = resolvedData[key];
    if (value && typeof value.path === 'string' && value.path.includes('/')) {
       try {
        const docRef = doc(firestore, value.path);
        const docSnap = await getDoc(docRef);
        if (docSnap.exists()) {
          resolvedData[key] = { id: docSnap.id, ...processDocValue(docSnap.data()) };
        }
      } catch (error) {
        console.error(`Error resolving reference for path: ${value.path}`, error);
      }
    }
  }
  return resolvedData;
}


export function useCollection<T>(
  ref: CollectionReference | Query | null,
  options?: UseCollectionOptions
) {
  const [data, setData] = useState<T[] | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<Error | null>(null);

  const memoizedOptions = useMemo(() => options, [JSON.stringify(options)]);

  useEffect(() => {
    if (!ref) {
      setLoading(false);
      return;
    }

    let q = query(ref);

    if (memoizedOptions?.where) {
      memoizedOptions.where.forEach((w) => {
        q = query(q, where(w[0], w[1], w[2]));
      });
    }

    if (memoizedOptions?.orderBy) {
      q = query(q, orderBy(memoizedOptions.orderBy[0], memoizedOptions.orderBy[1]));
    }

    if (memoizedOptions?.limit) {
      q = query(q, limit(memoizedOptions.limit));
    }
    if (memoizedOptions?.startAt) {
      q = query(q, startAt(...memoizedOptions.startAt));
    }
    if (memoizedOptions?.startAfter) {
      q = query(q, startAfter(...memoizedOptions.startAfter));
    }
    if (memoizedOptions?.endAt) {
      q = query(q, endAt(...memoizedOptions.endAt));
    }
    if (memoizedOptions?.endBefore) {
      q = query(q, endBefore(...memoizedOptions.endBefore));
    }

    const unsubscribe = onSnapshot(
      q,
      async (snapshot) => {
        try {
          const docs = await Promise.all(snapshot.docs.map(async (doc) => {
            const docData = doc.data();
            const processedData = processDocValue(docData);
            const resolvedData = await resolveReferences(processedData, ref.firestore);
            return { id: doc.id, ...resolvedData } as T;
          }));
          setData(docs);
        } catch (e: any) {
           setError(e);
        } finally {
           setLoading(false);
        }
      },
      (err) => {
        setError(err);
        setLoading(false);
      }
    );

    return () => unsubscribe();
  }, [ref, memoizedOptions]);

  return { data, loading, error };
}
