// This file is automatically generated by Firebase Studio.
// Do not edit this file manually.

import { initializeApp, getApp, getApps, FirebaseOptions } from 'firebase/app';
import { getAuth } from 'firebase/auth';
import { getFirestore } from 'firebase/firestore';

const firebaseConfig: FirebaseOptions = {
  "projectId": "kra-dashboard-7zwcr",
  "appId": "1:312075972890:web:e919b0632350589f8e3ca3",
  "storageBucket": "kra-dashboard-7zwcr.appspot.com",
  "apiKey": "AIzaSyA3z4_7tMgAdB0rrTNo8R3gka-FLWixj2A",
  "authDomain": "kra-dashboard-7zwcr.firebaseapp.com",
  "messagingSenderId": "312075972890"
};

export function initializeFirebase() {
  if (getApps().length > 0) {
    return {
      firebaseApp: getApp(),
      firestore: getFirestore(),
      auth: getAuth(),
    };
  }

  const firebaseApp = initializeApp(firebaseConfig);

  return {
    firebaseApp,
    firestore: getFirestore(firebaseApp),
    auth: getAuth(firebaseApp),
  };
}
