// This file is automatically generated by Firebase Studio.
// Do not edit this file manually.

export { initializeFirebase } from './config';
export { FirebaseProvider } from './provider';
export { FirebaseClientProvider } from './client-provider';

// Hooks
export { useFirebase, useFirebaseApp, useFirestore, useAuth } from './provider';
export { useUser } from './auth/use-user';
export { useCollection } from './firestore/use-collection';
export { useDoc } from './firestore/use-doc';
