// This file is automatically generated by Firebase Studio.
// Do not edit this file manually.

'use client';

import { createContext, useContext, ReactNode } from 'react';
import type { FirebaseApp } from 'firebase/app';
import type { Auth } from 'firebase/auth';
import type { Firestore } from 'firebase/firestore';

export interface FirebaseContextValue {
  firebaseApp: FirebaseApp | null;
  auth: Auth | null;
  firestore: Firestore | null;
}

const FirebaseContext = createContext<FirebaseContextValue>({
  firebaseApp: null,
  auth: null,
  firestore: null,
});

export interface FirebaseProviderProps extends Partial<FirebaseContextValue> {
  children: ReactNode;
}

export function FirebaseProvider({
  children,
  firebaseApp = null,
  auth = null,
  firestore = null,
}: FirebaseProviderProps) {
  return (
    <FirebaseContext.Provider value={{ firebaseApp, auth, firestore }}>
      {children}
    </FirebaseContext.Provider>
  );
}

export const useFirebase = () => useContext(FirebaseContext);

export const useFirebaseApp = () => {
  const { firebaseApp } = useFirebase();
  if (!firebaseApp) {
    throw new Error(
      'useFirebaseApp must be used within a FirebaseProvider with a FirebaseApp instance.'
    );
  }
  return firebaseApp;
};

export const useAuth = () => {
  const { auth } = useFirebase();
  if (!auth) {
    throw new Error(
      'useAuth must be used within a FirebaseProvider with an Auth instance.'
    );
  }
  return auth;
};

export const useFirestore = () => {
  const { firestore } = useFirebase();
  if (!firestore) {
    throw new Error(
      'useFirestore must be used within a FirebaseProvider with a Firestore instance.'
    );
  }
  return firestore;
};
